/**
 * Standard default priorities & wants for UK home movers.
 */

import { WantCriterion } from '../../types/wants';

export const DEFAULT_WANTS: WantCriterion[] = [
  {
    id: 'want_bedrooms',
    group: 'general',
    title: 'At least 3 bedrooms',
    description: 'Master bedroom, guest room, and flexible office/nursery',
    importance: 'must_have',
    valueType: 'min_number',
    targetValue: 3,
    fieldKey: 'bedrooms',
  },
  {
    id: 'want_bathrooms',
    group: 'general',
    title: 'At least 2 bathrooms',
    description: 'Family bathroom plus second facility',
    importance: 'important',
    valueType: 'min_number',
    targetValue: 2,
    fieldKey: 'bathrooms',
  },
  {
    id: 'want_parking',
    group: 'general',
    title: 'Off-street driveway parking',
    description: 'Private parking for at least 1 car',
    importance: 'must_have',
    valueType: 'min_number',
    targetValue: 1,
    fieldKey: 'parkingSpaces',
  },
  {
    id: 'want_garden',
    group: 'general',
    title: 'Sunny South or West facing garden',
    description: 'Maximise evening daylight in summer',
    importance: 'important',
    valueType: 'enum',
    targetValue: 'south_or_west',
    fieldKey: 'gardenOrientation',
  },
  {
    id: 'want_en_suite',
    group: 'general',
    title: 'En suite bathroom to master',
    description: 'Private shower room for the main bedroom',
    importance: 'important',
    valueType: 'boolean',
    targetValue: true,
    fieldKey: 'hasEnSuite',
  },
  {
    id: 'want_downstairs_wc',
    group: 'general',
    title: 'Downstairs guest WC / cloakroom',
    description: 'Ground floor convenience for visitors',
    importance: 'important',
    valueType: 'boolean',
    targetValue: true,
    fieldKey: 'hasDownstairsWc',
  },
  {
    id: 'want_home_office',
    group: 'general',
    title: 'Dedicated study or home office',
    description: 'Quiet room for remote working',
    importance: 'nice_to_have',
    valueType: 'boolean',
    targetValue: true,
    fieldKey: 'hasHomeOfficeOrStudy',
  },
  {
    id: 'want_loft_storage',
    group: 'general',
    title: 'Boarded or converted loft storage',
    description: 'Clean, accessible storage via pull-down ladder',
    importance: 'nice_to_have',
    valueType: 'enum',
    targetValue: 'boarded_or_converted',
    fieldKey: 'loftStatus',
  },
  {
    id: 'want_epc',
    group: 'general',
    title: 'Energy efficient home (EPC Band C or above)',
    description: 'Comfortable thermal performance and lower bills',
    importance: 'important',
    valueType: 'enum',
    targetValue: 'C_or_above',
    fieldKey: 'epcRating',
  },
  {
    id: 'want_chain_free',
    group: 'general',
    title: 'No onward chain / chain free',
    description: 'Smoother transaction with minimal risk of collapse',
    importance: 'nice_to_have',
    valueType: 'boolean',
    targetValue: true,
    fieldKey: 'chainStatus',
  },
];
